version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    ports: 
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin