name: CI

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*
      - release/*
  release:
    types: [published]
  pull_request: {}

jobs:
  golang:
    uses: UNIwise/workflows/.github/workflows/golang.yaml@master
    secrets: inherit
    with:
      go-version: 1.23
      golangci-lint-version: v1.61.0
      platforms: linux/amd64,linux/arm64